services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  worker1:
    build: .
    container_name: celery_worker_1
    command: celery -A app.celery_app.celery_app worker --loglevel=info --concurrency 2
    depends_on:
      - redis
    environment:
      - PYTHONPATH=.
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
  flower:
    build: .
    container_name: flower
    command: celery -A app.celery_app.celery_app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker1
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0